[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
hub_evidence_anchor = "275QQuz5D6d5U7rhAVW1gYGZBmmyzq6srFdV3rT6rMdA"

[provider]
cluster = "devnet"
wallet = "/tmp/deploy-wallet.json"

[scripts]
test = "yarn run mocha -t 300000 --timeout 600000 tests/"

[hooks]
[programs.hub_evidence_anchor]
hub_evidence_anchor = "6dap1barBURnSHW3qYMg7JK6iZGFUWWWMLSx4Qynbqek"
