[programs.devnet]
hub_evidence_anchor = "spJAH8mpJmzp6xf5fpfueaBsjRUbPjcmJJMTrfvW8cf"

[provider]
cluster = "devnet"
wallet = "/tmp/deploy-wallet.json"

[scripts]
test = "yarn run mocha -t 300000 --timeout 600000 tests/"
