on:
  workflow_dispatch:
    inputs:
      skip_build:
        description: Skip build
        default: 'false'

name: Build and Deploy to Mainnet-Beta

permissions:
  contents: read
  attestations: write
  id-token: write

env:
  CARGO_HOME: /opt/cargo
  RUSTUP_HOME: /opt/rustup
  RUSTUP_TOOLCHAIN: "1.85"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Solana CLI
        run: |
          curl -sSfL https://github.com/anza-xyz/agave/releases/download/v3.1.12/solana-release-x86_64-unknown-linux-gnu.tar.bz2 | tar jx
          mv solana-release /tmp/solana-release
          echo "/tmp/solana-release/bin" >> $GITHUB_PATH
          /tmp/solana-release/bin/solana --version
